* Bonet-Monroig, X. and Sagastizabal, R. and Singh,                  M. and O’Brien, T. E. (2018): Low-cost error mitigation by symmetry verification
:PROPERTIES:
:Custom_id: BSSO18:low
:END:
- H is evolution Hamiltonian that we seek to implement.
- S is a symmetry operator at all times, [H,S] = 0.
- S can also be constructed from a subspace that is invariant by H (if that's what is given).
- Best is when the subspace that we want to stay in can be characterized via a Pauli measurement. 

- Mitigation is done by measuring S mid-way (bulk symmetry verification) or at the end (final symmetry verification).
- Do the measurement with an ancilla (possibly with swaps to avoid long range interaction)
- Do the measurement with an ancilla embedded in the computation (not so clear as there are many ways of doing this).
- Do classical post-processing when computing expectation values (and final symmetry verification)


** Idea
- Can reproduce the same with more complex symmetres as long as we can characterize the subspace through local (or k-local) operations.
- What is the possible error propagation incurred by the ancilla methods? can we improve it with bias qubits?
- Use Shadows to optimally get the values that we will recompose later to get the traces that are involved into the post-processing method. Can we do it also with "mid" way measurements / partial shadows?
- Connect this to Luca Dellantonio Technique???
